# All action to implement in Github
name: Build an test

on:
  push:
    branches-ignore:
      - "qa"
      - "master"
env:
  work_directory: ./functions

jobs:
  build:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ${{ env.work_directory }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Restore cache
        uses: actions/cache@v2
        env:
          cache-name: nodejs-github-actions
        with:
          path: node_modules
          key: npm-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: npm-${{ env.cache-name }}
      - name: Install Dependencies
        run: npm install
      - name: list dir
        run: ls -l
  test:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ${{ env.work_directory }}
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Restore cache
        uses: actions/cache@v2
        env:
          cache-name: nodejs-github-actions
        with:
          path: node_modules
          key: npm-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: npm-${{ env.cache-name }}
      - name: Listar Directorio
        run: ls -l
