name: Production Deploy

on:
  push:
    branches: [ master ]
env:
  function-dir: functions
defaults:
  run:
    working-directory: functions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Cache Dependencies
      uses: actions/cache@v2
      env:
        cache-name: nodejs-github-actions
      with:
        path: ${{ env.function-dir }}/node_modules
        key: npm-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}-v1
    - name: Install dependencies
      run: npm install
    - name: Prepare Function
      run: npm run build
    - name: Share build folder
      uses: actions/upload-artifact@v1
      with:
        name: lib
        path: ${{ env.function-dir }}/lib
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Restore cache
        uses: actions/cache@v2
        env:
          cache-name: nodejs-github-actions
        with:
          path: ${{ env.function-dir }}/node_modules
          key: npm-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}-v1
      - name: Execute tests
        run: npm run lint
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Restore cache
        uses: actions/cache@v2
        env:
          cache-name: nodejs-github-actions
        with:
          path: ${{ env.function-dir }}/node_modules
          key: npm-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}-v1
      - name: Get build dir
        uses: actions/download-artifact@v1
        with:
          name: lib
      - name: Checkout danielmillan/pipelines-firebase-functions
        uses: actions/checkout@v2
        with:
          repository: danielmillan/pipelines-firebase-functions
          ref: '1.0.1'
          token: ${{ secrets.CA_GITHUB_TOKEN }}
          persist-credentials: false
          path: ./.github/actions/pipelines-firebase-functions
      - name: Deploy function
        uses: ./.github/actions/pipelines-firebase-functions
        with:
          firebase-token: ${{ secrets.FIREBASE_TOKEN }}
          resources-name: lib
          project-name: bms-software
